services:
  backpain_app:
    build: .
    container_name: backpain_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
    depends_on:
      - signoz_collector

  signoz_collector:
    image: signoz/signoz-otel-collector:latest
    container_name: signoz_collector
    ports:
      - "4317:4317"
      - "55681:55681"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

  signoz_query:
    image: signoz/signoz-query-service:latest
    container_name: signoz_query
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_URL=clickhouse://clickhouse:9000/default
      - QUERY_SERVICE_CONFIG_FILE=/etc/signoz/config.yaml

  signoz_frontend:
    image: signoz/frontend:latest  # Corrected image name
    container_name: signoz_frontend
    ports:
      - "3301:3301"
    environment:
      - REACT_APP_API_ENDPOINT=http://localhost:8080
